/* @flow */

export const PREVIEWS_FETCH_REQUESTED = 'PREVIEWS_FETCH_REQUESTED';
export const PREVIEWS_FETCH_SUCCEEDED = 'PREVIEWS_FETCH_SUCCEEDED';
export const PREVIEWS_FETCH_FAILED = 'PREVIEWS_FETCH_FAILED';
export const PREVIEW_UPDATE_SUCCEEDED = 'PREVIEW_UPDATE_SUCCEEDED';
export const PREVIEW_UPDATE_FAILED = 'PREVIEW_UPDATE_FAILED';
export const PREVIEW_EDIT_STARTED = 'PREVIEW_EDIT_STARTED';
export const PREVIEW_EDIT_STOPPED = 'PREVIEW_EDIT_STOPPED';
export const NOTIFICATION_OPENED = 'NOTIFICATION_OPENED';
